version: '3.8'

services:
  mysql:
    image: mysql:8.0.41
    networks:
      - backend-ntwk
    volumes:
      - sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Make sure do chmod 600 .env to protect credentials better.
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  wordpress:
    image: wordpress:6.7.2
    ports:
      - "8080:80"
    networks:
      - frontend-ntwk
      - backend-ntwk
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql

volumes:
  sql-data:

networks:
  backend-ntwk:
    external: true
  frontend-ntwk:
    external: true